In [1]:
from captum_playground import CaptumInterpreter

In [2]:
captum_interpreter = CaptumInterpreter(
    method='LayerIntergratedGradients',
    model_path='models/sa_head.pt',
    pretrained_name_or_path='models/bdi-roberta',
    tokenizer_path='models/bdi-tokenizer',
    device='cpu',
    is_visualize=True
)

In [3]:
a = captum_interpreter.interpret_sample(
    text="xe vinfast rất tệ",
    max_length=200,
    label=0,
    target=0
)
a

(array([-0.03101242, -0.15081399, -0.72819374, -0.50489279,  0.42229405,
         0.11304095]),
 tensor([-3.2516], dtype=torch.float64),
 0.9199813604354858,
 0,
 tensor([[    0,  4767, 38436,   597,  2799,     2]]))

In [7]:
captum_interpreter.visualize_samples(
    text=["xe vinfast ok mà", "xe vinfast rất tệ"],
    max_length=200,
    label=[1, 0],
    target=[1, 0]
)

attributions: [-0.03021361 -0.14450266  0.93620428  0.2540396 ] 
 text: ['xe', ' vinfast', ' ok', ' mà']
attributions: [-0.15081399 -0.72819374 -0.50489279  0.42229405] 
 text: ['xe', ' vinfast', ' rất', ' tệ']
